ansible_user: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:user') }}"
ansible_ssh_host: "{{ lookup('hashi_vault', 'secret=kv/data/matrix:ipv4') }}"
ansible_port: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:port') }}"
ansible_ssh_private_key_file: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:key') }}"
hostname_to_add: "{{ lookup('hashi_vault', 'secret=kv/data/matrix:domain') }}"
