package_update: true
debian_base_packages:
  - ca-certificates
  - curl
  - containerd.io
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - git
  - gnupg
  - netfilter-persistent
matrix_domain: m1k.cloud
