services:

  certbot:
    container_name: certbot
    image: docker.io/gbeine/dns-hetzner:v2.0.1
    volumes:
      - /docker/certbot/certbot_etc:/etc/letsencrypt
      - /docker/certbot/hetzner.ini:/root/hetzner.ini
    command: >-
      certonly
      --authenticator dns-hetzner
      --dns-hetzner-credentials /root/hetzner.ini
      --dns-hetzner-propagation-seconds 60
      --email {{ acme_certificate_email }}
      --agree-tos --no-eff-email
      --keep-until-expiring
      -d "{{ acme_base_domain }},{{ acme_certificate_domain_wildcard }}"
    networks:
      - container_network

networks:
  container_network:
    name: container_network
    enable_ipv6: true
