services:
  certbot:
    container_name: certbot
    image: ghcr.io/ironashram/certbot-dns-hetzner-cloud:0.1
    volumes:
      - /docker/certbot/certbot_etc:/etc/letsencrypt
      - /docker/certbot/hetzner.ini:/root/hetzner.ini
    command: >-
      certonly
      --authenticator dns-hetzner-cloud
      --dns-hetzner-cloud-credentials /root/hetzner.ini
      --dns-hetzner-cloud-propagation-seconds 120
      --email {{ acme_certificate_email }}
      --agree-tos --no-eff-email
      --keep-until-expiring
      -d "{{ acme_base_domain }},{{ acme_certificate_domain_wildcard }}"
    networks:
      - container_network

networks:
  container_network:
    name: container_network
    enable_ipv6: true
