services:

  haproxy:
    container_name: haproxy
    image: docker.io/haproxy:3.2.4
    restart: "always"
    volumes:
      - /docker/matrix/haproxy_conf:/usr/local/etc/haproxy
      - /docker/certbot/certbot_etc/live/{{ matrix_base_domain }}/fullchain.pem:/usr/local/etc/certs/fullchain.pem:ro
      - /docker/certbot/certbot_etc/live/{{ matrix_base_domain }}/privkey.pem:/usr/local/etc/certs/fullchain.pem.key:ro
    network_mode: host
    user: root

  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:v1.138.0
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yml
    volumes:
      - /docker/matrix/synapse_data:/data:rw
    depends_on:
      - synapse-db
    ports:
      - "8008:8008"
    networks:
      - container_network

  synapse-db:
    container_name: synapse-db
    image: docker.io/postgres:17.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER={{ matrix_db_user }}
      - POSTGRES_PASSWORD={{ matrix_db_password }}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - /docker/matrix/synapse_data/db:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - container_network

networks:
  container_network:
    external: true
    name: container_network
