version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "ansible/files/certbot"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "ansible/files/mailserver"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "ansible/files/matrix"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "ansible/files/monitoring"
    schedule:
      interval: "daily"
