# Set update schedule for GitHub Actions

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "files/certbot"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "files/mailserver"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "files/matrix"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "files/monitoring"
    schedule:
      interval: "daily"
