services:

  nginx:
    container_name: nginx
    image: docker.io/nginx:1.25.4
    restart: "always"
    volumes:
      - /docker/matrix/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/certbot/certbot_etc:/etc/letsencrypt
    network_mode: host

  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:v1.102.0
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yml
    volumes:
      - /docker/matrix/synapse_data:/data:rw
    depends_on:
      - synapse-db
    ports:
      - "8008:8008"
    networks:
      - container_network

  synapse-db:
    container_name: synapse-db
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER={{ matrix_db_user }}
      - POSTGRES_PASSWORD={{ matrix_db_password }}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - /docker/matrix/synapse_data/db:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - container_network

  sliding-proxy:
    container_name: sliding-proxy
    image: ghcr.io/matrix-org/sliding-sync:v0.99.15
    restart: always
    environment:
      - "SYNCV3_SECRET={{ matrix_sliding_sync_secret }}"
      - "SYNCV3_SERVER=http://synapse:8008"
      - "SYNCV3_BINDADDR=0.0.0.0:8009"
      - "SYNCV3_DB=user=syncv3 dbname=syncv3 sslmode=disable host=sliding-postgres password={{ matrix_sliding_sync_db_password }}"
    depends_on:
      - synapse
      - sliding-postgres
    ports:
      - "8009:8009"
    networks:
      - container_network

  sliding-postgres:
    container_name: sliding-postgres
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=syncv3"
      - "POSTGRES_PASSWORD={{ matrix_sliding_sync_db_password }}"
      - "POSTGRES_DB=syncv3"
    volumes:
      - /docker/matrix/synapse_data/sliding_sync_db:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - container_network

networks:
  container_network:
    external: true
    name: container_network
