version: '3'

services:

  nginx:
    image: "nginx:1.25.3"
    restart: "always"
    volumes:
      - /docker/matrix/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

  synapse:
    image: "docker.io/matrixdotorg/synapse:v1.98.0"
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - /docker/matrix/synapse_data:/data:rw
