services:

  nginx:
    container_name: nginx
    image: docker.io/nginx:1.27.4
    restart: "always"
    volumes:
      - /docker/matrix/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/certbot/certbot_etc:/etc/letsencrypt
    network_mode: host

  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:v1.124.0
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yml
    volumes:
      - /docker/matrix/synapse_data:/data:rw
    depends_on:
      - synapse-db
    ports:
      - "8008:8008"
    networks:
      - container_network

  synapse-db:
    container_name: synapse-db
    image: docker.io/postgres:17.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER={{ matrix_db_user }}
      - POSTGRES_PASSWORD={{ matrix_db_password }}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - /docker/matrix/synapse_data/db:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - container_network

networks:
  container_network:
    external: true
    name: container_network
