---
- name: Configure Instances
  hosts: cloud_self_hosted
  gather_facts: true
  tasks:
    - name: Distribution
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }}"

    - name: Debian packages
      ansible.builtin.import_tasks: tasks/pkg_debian.yml
      when: ansible_os_family == 'Debian'
      tags: packages

    - name: Configure Firewall
      ansible.builtin.import_tasks: tasks/firewall_debian.yml
      when: ansible_os_family == 'Debian'
      tags: firewall


  handlers:
    - name: Flush iptables
      ansible.builtin.iptables:
        flush: true
