---
- name: Dynamic Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add Hosts
      ansible.builtin.add_host:
        name: "{{ dynamic_hostname }}"
        groups: self_hosted
      tags: ['packages', 'iptables', 'certbot', 'matrix', 'mailserver', 'monitoring']
      changed_when: false

- name: Configure Personal Services
  hosts: self_hosted
  gather_facts: true
  tasks:
    - name: Install Packages
      ansible.builtin.import_tasks: tasks/pkg.yml
      tags: packages

    - name: Configure Iptables
      ansible.builtin.import_tasks: tasks/iptables.yml
      tags: iptables

    - name: Configure Certbot
      ansible.builtin.import_tasks: tasks/certbot.yml
      tags: certbot

    - name: Configure Matrix
      ansible.builtin.import_tasks: tasks/matrix.yml
      tags: matrix

    - name: Configure Mail Server
      ansible.builtin.import_tasks: tasks/mailserver.yml
      tags: mailserver

    - name: Configure Monitoring
      ansible.builtin.import_tasks: tasks/monitoring.yml
      tags: monitoring

  handlers:
    - name: Flush iptables
      ansible.builtin.iptables:
        flush: true

    - name: Apply ipv4 iptables rules
      community.general.iptables_state:
        state: restored
        path: /etc/iptables/rules.v4
      async: "{{ ansible_timeout }}"
      poll: 0

    - name: Apply ipv6 iptables rules
      community.general.iptables_state:
        state: restored
        path: /etc/iptables/rules.v6
        ip_version: ipv6
      async: "{{ ansible_timeout }}"
      poll: 0

    - name: Restart Docker
      ansible.builtin.systemd_service:
        name: docker.service
        state: restarted

    - name: Docker Compose Up - Certbot
      community.docker.docker_compose_v2:
        project_src: /docker/certbot
        state: present
        recreate: auto
        remove_orphans: true
      when: "'certbot' in ansible_tags"
      listen: "Docker Compose Up"

    - name: Docker Compose Up - Monitoring
      community.docker.docker_compose_v2:
        project_src: /docker/monitoring
        state: present
        recreate: auto
        remove_orphans: true
      when: "'monitoring' in ansible_tags"
      listen: "Docker Compose Up"

    - name: Docker Compose Up - Matrix
      community.docker.docker_compose_v2:
        project_src: /docker/matrix
        state: present
        recreate: auto
        remove_orphans: true
      when: "'matrix' in ansible_tags"
      listen: "Docker Compose Up"

    - name: Docker Compose Up - Mail
      community.docker.docker_compose_v2:
        project_src: /docker/mail
        state: present
        recreate: auto
        remove_orphans: true
      when: "'mailserver' in ansible_tags"
      listen: "Docker Compose Up"
