---
- name: Dynamic Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add Hosts
      ansible.builtin.add_host:
        name: "{{ hostname_to_add }}"
        groups: self_hosted
      tags:
        - packages
        - iptables
        - certbot
        - matrix
        - mailserver

- name: Configure Personal Services
  hosts: self_hosted
  gather_facts: true
  tasks:
    - name: Print Ansible Distribution
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }}"

    - name: Install Packages
      ansible.builtin.import_tasks: tasks/pkg.yml
      tags: packages

    - name: Configure Iptables
      ansible.builtin.import_tasks: tasks/iptables.yml
      tags: iptables

    - name: Configure Certbot
      ansible.builtin.import_tasks: tasks/certbot.yml
      tags: certbot

    - name: Configure Matrix
      ansible.builtin.import_tasks: tasks/matrix.yml
      tags: matrix

    - name: Configure Mail Server
      ansible.builtin.import_tasks: tasks/mailserver.yml
      tags: mailserver

  handlers:
    - name: Flush iptables
      ansible.builtin.iptables:
        flush: true

    - name: Certbot Compose Down
      community.docker.docker_compose:
        project_src: /docker/certbot
        state: absent

    - name: Certbot Compose Up
      community.docker.docker_compose:
        project_src: /docker/certbot

    - name: Matrix Compose Down
      community.docker.docker_compose:
        project_src: /docker/matrix
        state: absent

    - name: Matrix Compose Up
      community.docker.docker_compose:
        project_src: /docker/matrix

    - name: Mailserver Compose Down
      community.docker.docker_compose:
        project_src: /docker/mail
        state: absent

    - name: Mailserver Compose Up
      community.docker.docker_compose:
        project_src: /docker/mail

    - name: Restart Docker
      ansible.builtin.systemd_service:
        name: docker.service
        state: restarted

    - name: Apply ipv4 iptables rules
      community.general.iptables_state:
        state: restored
        path: /etc/iptables/rules.v4
      async: "{{ ansible_timeout }}"
      poll: 0
      notify:
        - Restart Docker

    - name: Apply ipv6 iptables rules
      community.general.iptables_state:
        state: restored
        path: /etc/iptables/rules.v6
        ip_version: ipv6
      async: "{{ ansible_timeout }}"
      poll: 0
      notify:
        - Restart Docker
