---
- name: Dynamic Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add Hosts
      ansible.builtin.add_host:
        name: "{{ lookup('hashi_vault', 'secret=kv/data/matrix:domain') }}"
        groups: cloud_self_hosted
        ansible_user: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:user') }}"
        ansible_ssh_host: "{{ lookup('hashi_vault', 'secret=kv/data/matrix:ipv4') }}"
        ansible_port: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:port') }}"
        ansible_ssh_private_key_file: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:key') }}"
      tags:
        - packages
        - iptables
        - certbot
        - matrix
        - mailserver

- name: Configure Personal Services
  hosts: cloud_self_hosted
  gather_facts: true
  tasks:
    - name: Print Ansible Distribution
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }}"

    - name: Install Packages
      ansible.builtin.import_tasks: tasks/pkg.yml
      tags: packages

    - name: Configure Iptables
      ansible.builtin.import_tasks: tasks/iptables.yml
      tags: iptables

    - name: Configure Certbot
      ansible.builtin.import_tasks: tasks/certbot.yml
      tags: certbot

    - name: Configure Matrix
      ansible.builtin.import_tasks: tasks/matrix.yml
      tags: matrix

    - name: Configure Mail Server
      ansible.builtin.import_tasks: tasks/mailserver.yml
      tags: mailserver

  handlers:
    - name: Flush iptables
      ansible.builtin.iptables:
        flush: true

    - name: Certbot Compose Down
      community.docker.docker_compose:
        project_src: /docker/certbot
        state: absent

    - name: Certbot Compose Up
      community.docker.docker_compose:
        project_src: /docker/certbot

    - name: Matrix Compose Down
      community.docker.docker_compose:
        project_src: /docker/matrix
        state: absent

    - name: Matrix Compose Up
      community.docker.docker_compose:
        project_src: /docker/matrix

    - name: Mailserver Compose Down
      community.docker.docker_compose:
        project_src: /docker/mail
        state: absent

    - name: Mailserver Compose Up
      community.docker.docker_compose:
        project_src: /docker/mail

    - name: Restart Docker
      ansible.builtin.systemd_service:
        name: docker.service
        state: restarted
