version: '3'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.3.1
    container_name: mailserver
    hostname: "{{ mail_host }}"
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP
      - "143:143"  # IMAP4
      - "465:465"  # ESMTP
      - "587:587"  # ESMTP
      - "993:993"  # IMAP4
    volumes:
      - /docker/mail/mail-data/:/var/mail/
      - /docker/mail/mail-state/:/var/mail-state/
      - /docker/mail/mail-logs/:/var/log/mail/
      - /docker/mail/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /docker/certbot/certbot_etc:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  default:
    enable_ipv6: true
