services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:edge@sha256:a80c6c74f95b6ceecca00ad9bdbe0b67e87daadc777621b4b6bb961c009f60af
    container_name: mailserver
    hostname: "{{ mail_host }}"
    env_file: mailserver.env
    volumes:
      - /docker/mail/mail-data/:/var/mail/
      - /docker/mail/mail-state/:/var/mail-state/
      - /docker/mail/mail-logs/:/var/log/mail/
      - /docker/mail/config/:/tmp/docker-mailserver/
      - /docker/mail/fail2ban-jail.local:/etc/fail2ban/jail.d/user-jail.local:ro
      - /docker/mail/rspamd-dkim_signing.conf:/etc/rspamd/override.d/dkim_signing.conf:ro
      - /docker/mail/rspamd-dkim.private:/etc/rspamd/dkim/mail.private:ro
      - /etc/localtime:/etc/localtime:ro
      - /docker/certbot/certbot_etc:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    network_mode: host
