---
- name: mailserver | Set tags fact
  ansible.builtin.set_fact:
    ansible_tags: "{{ ansible_tags | default([]) + ['mailserver'] }}"

- name: mailserver | Create docker compose folders
  ansible.builtin.file:
    path: /docker/mail/{{ item }}
    state: directory
    mode: "0755"
    recurse: false
  loop:
    - mail-data
    - mail-state
    - mail-logs
    - config

- name: mailserver | Template mailserver.env
  ansible.builtin.template:
    src: files/mailserver/mailserver.env.j2
    dest: /docker/mail/mailserver.env
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up

- name: mailserver | Template docker-compose.yml
  ansible.builtin.template:
    src: files/mailserver/docker-compose.yml
    dest: /docker/mail/docker-compose.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up

- name: mailserver | Check Postfix Users
  ansible.builtin.stat:
    path: /docker/mail/config/postfix-accounts.cf
  register: accounts

- name: mailserver | Create Postfix Users
  community.docker.docker_container_exec:
    container: mailserver
    argv:
      - setup
      - email
      - add
      - "{{ item.email }}"
      - "{{ item.password }}"
  loop:
    - "{{ postfix_users }}"
  when: "not accounts.stat.exists"
  no_log: true

- name: mailserver | Check Postfix Alias
  ansible.builtin.stat:
    path: /docker/mail/config/postfix-virtual.cf
  register: alias

- name: mailserver | Create Postmaster Alias
  community.docker.docker_container_exec:
    container: mailserver
    argv:
      - setup
      - alias
      - add
      - "{{ item.alias }}"
      - "{{ item.email }}"
  loop:
    - "{{ postfix_aliases }}"
  when: "not alias.stat.exists"
  no_log: true

- name: mailserver | Check OpenDKIM
  ansible.builtin.stat:
    path: "{{ opendkim_folder }}"
  register: opendkim

- name: mailserver | Setup OpenDKIM
  community.docker.docker_container_exec:
    container: mailserver
    argv:
      - setup
      - config
      - dkim
  when: "not opendkim.stat.exists"
