---
- name: matrix | Create docker compose folders
  ansible.builtin.file:
    path: /docker/matrix/{{ item }}
    state: directory
    mode: "0755"
    recurse: false
  loop:
    - nginx_conf

- name: matrix | Create synapse folders
  ansible.builtin.file:
    path: /docker/matrix/{{ item }}
    state: directory
    mode: "0755"
    owner: 991
    group: 991
    recurse: false
  loop:
    - synapse_data
    - synapse_data/db
    - synapse_data/media_store
    - synapse_data/sliding_sync_db

- name: matrix | Template nginx conf
  ansible.builtin.template:
    src: files/matrix/nginx.conf.j2
    dest: /docker/matrix/nginx_conf/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Down
    - Docker Compose Up

- name: matrix | Template synapse homeserver.yml
  ansible.builtin.template:
    src: files/matrix/homeserver.yml.j2
    dest: /docker/matrix/synapse_data/homeserver.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up

- name: matrix | Template homeserver.signing.key
  ansible.builtin.template:
    src: files/matrix/homeserver.signing.key.j2
    dest: /docker/matrix/synapse_data/homeserver.signing.key
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up

- name: matrix | Template docker-compose.yml
  ansible.builtin.template:
    src: files/matrix/docker-compose.yml
    dest: /docker/matrix/docker-compose.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up
