---
- name: matrix | Create docker compose folders
  ansible.builtin.file:
    path: /docker/matrix/{{ item }}
    state: directory
    mode: "0755"
    recurse: false
  loop:
    - nginx_conf
    - synapse_data
    - synapse_data/db
    - synapse_data/media_store
    - synapse_data/sliding_sync_db

- name: matrix | Template nginx conf
  ansible.builtin.template:
    src: files/matrix/matrix-nginx.conf.j2
    dest: /docker/matrix/nginx_conf/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Matrix Compose Down
    - Matrix Compose Up

- name: matrix | Template synapse homeserver.yaml
  ansible.builtin.template:
    src: files/matrix/homeserver.yaml.j2
    dest: /docker/matrix/synapse_data/homeserver.yaml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Matrix Compose Down
    - Matrix Compose Up

- name: matrix | Template homeserver.signing.key
  ansible.builtin.template:
    src: files/matrix/homeserver.signing.key.j2
    dest: /docker/matrix/synapse_data/homeserver.signing.key
    owner: root
    group: root
    mode: "0644"
  notify:
    - Matrix Compose Down
    - Matrix Compose Up

- name: matrix | Template docker-compose.yaml
  ansible.builtin.template:
    src: files/matrix/docker-compose.yaml.j2
    dest: /docker/matrix/docker-compose.yaml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Matrix Compose Down
    - Matrix Compose Up
