---
- name: certbot | Set tags fact
  ansible.builtin.set_fact:
    ansible_tags: "{{ ansible_tags | default([]) + ['certbot'] }}"

- name: certbot | Create docker compose folders
  ansible.builtin.file:
    path: /docker/certbot/{{ item }}
    state: directory
    mode: "0755"
    recurse: false
  loop:
    - certbot_etc

- name: certbot | Template hetzner.ini
  ansible.builtin.template:
    src: files/certbot/hetzner.ini.j2
    dest: /docker/certbot/hetzner.ini
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up

- name: certbot | Add certbot renewal cronjob
  ansible.builtin.cron:
    name: "certbot renewal cronjob"
    cron_file: certbot_hetzner
    job: "docker start certbot"
    user: "root"
    special_time: "daily"

- name: certbot | Template docker-compose.yml
  ansible.builtin.template:
    src: files/certbot/docker-compose.yml
    dest: /docker/certbot/docker-compose.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up
