---
- name: iptables | Set tags fact
  ansible.builtin.set_fact:
    ansible_tags: "{{ ansible_tags | default([]) + ['iptables'] }}"

- name: iptables | Create /etc/iptables
  ansible.builtin.file:
    path: /etc/iptables
    state: directory
    mode: "0755"

- name: iptables | Copy ipv4 rules file
  ansible.builtin.copy:
    src: files/iptables/rules.v4
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Apply ipv4 iptables rules

- name: iptables | Copy ipv6 rules file
  ansible.builtin.copy:
    src: files/iptables/rules.v6
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Apply ipv6 iptables rules
