---
- name: monitoring | Set tags fact
  ansible.builtin.set_fact:
    ansible_tags: "{{ ansible_tags | default([]) + ['monitoring'] }}"

- name: monitoring | Template docker-compose.yml
  ansible.builtin.template:
    src: files/monitoring/docker-compose.yml
    dest: /docker/monitoring/docker-compose.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Docker Compose Up
