---
- name: pkg | Refresh package database
  community.general.pacman:
    update_cache: true
  become: true
  changed_when: false

- name: pkg | Install required packages
  community.general.pacman:
    name: "{{ arch_base_packages }}"
    state: "{{ 'latest' if package_update | bool else 'present' }}"
  become: true

- name: pkg | Copy docker config.json
  ansible.builtin.copy:
    src: files/docker/config.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Docker
