---
- name: Ensure ssh config dir exists
  ansible.builtin.file:
    path: "{{ ssh_config_dir }}"
    state: directory
    mode: "0700"
  tags: always

- name: Write SSH known_hosts from Vault
  ansible.builtin.copy:
    content: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:known_hosts') }}"
    dest: "{{ ssh_config_dir }}/known_hosts"
    mode: "0644"
  tags: always

- name: Write SSH private key from Vault
  ansible.builtin.copy:
    content: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:private_key') }}"
    dest: "{{ ssh_config_dir }}/id_rsa"
    mode: "0600"
  no_log: true
  tags: always
