---
- name: Set configured port fact
  ansible.builtin.set_fact:
    configured_port: "{{ lookup('hashi_vault', 'secret=kv/data/ansible:port') }}"

- name: Check if we're using the default SSH port
  ansible.builtin.wait_for:
    port: "22"
    state: "started"
    host: "{{ ansible_host }}"
    connect_timeout: "3"
    timeout: "2"
  delegate_to: "localhost"
  ignore_errors: true
  register: default_ssh
  when: not ansible_check_mode

- name: Set inventory ansible_port to default
  ansible.builtin.set_fact:
    ansible_port: "22"
  when: not ansible_check_mode and
        default_ssh is defined and
        default_ssh.state is defined and
        default_ssh.state == "started"
  register: ssh_port_set

- name: Set inventory ansible_port to custom
  ansible.builtin.set_fact:
    ansible_port: "{{ configured_port }}"
  when: not ansible_check_mode and
        default_ssh is failed

- name: Check if we're using the inventory-provided SSH port
  ansible.builtin.wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ ansible_host }}"
    connect_timeout: "3"
    timeout: "2"
  delegate_to: "localhost"
  ignore_errors: true
  register: configured_ssh
  when: default_ssh is defined and
        default_ssh.state is undefined

- name: SSH port is configured properly
  ansible.builtin.debug:
    msg: "SSH port is configured properly"
  when: configured_ssh is defined and
        configured_ssh.state is defined and
        configured_ssh.state == "started"
  register: ssh_port_set

- name: Fail if SSH port was not auto-detected (unknown)
  ansible.builtin.fail:
    msg: "The SSH port is neither 22 or {{ ansible_port }}."
  when: ssh_port_set is undefined

- name: Confirm host connection works
  ansible.builtin.ping:

- name: Setup alternate SSH port
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ configured_port }}"
  notify: "Restart sshd"

- name: Ensure SSH is reloaded
  ansible.builtin.meta: flush_handlers

- name: Ensure we use the configured SSH port for the remainder of the role
  ansible.builtin.set_fact:
    ansible_port: "{{ configured_port }}"
