---
- name: Dynamic Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set up SSH config from Vault
      ansible.builtin.import_tasks: tasks/ssh_setup.yml

    - name: Add commstack
      ansible.builtin.add_host:
        name: commstack
      tags:
        - backup
      changed_when: false

    - name: Add coolify
      ansible.builtin.add_host:
        name: coolify
      tags:
        - backup
      changed_when: false

- name: Backup hosts
  hosts: commstack,coolify
  gather_facts: true
  tasks:
    - name: Run backup
      ansible.builtin.import_tasks: tasks/backup.yml
      tags: backup
