---
- name: Dynamic Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add commstack
      ansible.builtin.add_host:
        name: commstack
      tags:
        - backup
      changed_when: false

    - name: Add coolify
      ansible.builtin.add_host:
        name: coolify
      tags:
        - backup
      changed_when: false

- name: Backup hosts
  hosts: commstack,coolify
  gather_facts: true
  tasks:
    - name: Run backup
      ansible.builtin.import_tasks: tasks/backup.yml
      tags: backup

- name: Install backup crons
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install backup crons
      ansible.builtin.import_tasks: tasks/backup-cron.yml
      tags: cron
