services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro'
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
      - '--collector.tcpstat'
      - '--collector.processes'
      - '--collector.cgroups'
    pid: host
    security_opt:
      - apparmor=unconfined
    network_mode: host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
