services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro'
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
      - '--collector.tcpstat'
      - '--collector.processes'
      - '--collector.cgroups'
    pid: host
    security_opt:
      - apparmor=unconfined
    network_mode: host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: always
    expose:
      - 8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - container_network

  prometheus:
    image: quay.io/prometheus/prometheus:v2.50.1
    container_name: prometheus
    restart: always
    volumes:
      - /docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - container_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: docker.io/grafana/grafana:10.4.0
    container_name: grafana
    restart: always
    volumes:
      - /docker/monitoring/grafana/data:/var/lib/grafana
      - /docker/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - /docker/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER={{ grafana_user }}
      - GF_SECURITY_ADMIN_PASSWORD={{ grafana_password }}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://{{ grafana_domain }}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/node-exporter.json
    ports:
      - "3000:3000"
    networks:
      - container_network

networks:
  container_network:
    external: true
    name: container_network

