services:

  certbot:
    container_name: certbot
    image: docker.io/certbot/dns-cloudflare:v3.1.0
    volumes:
      - /docker/certbot/certbot_etc:/etc/letsencrypt
      - /docker/certbot/cloudflare.ini:/root/cloudflare.ini
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --email {{ acme_certificate_email }}
      --agree-tos --no-eff-email
      --keep-until-expiring
      -d "{{ acme_base_domain }},{{ acme_certificate_domain_wildcard }}"
    networks:
      - container_network

networks:
  container_network:
    name: container_network
    enable_ipv6: true
