name: Deploy Certbot

on:
  push:
    branches:
      - master
    paths:
      - 'ansible/files/certbot/**'
      - 'ansible/tasks/certbot.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/ansible-base.yaml
    with:
      tags: certbot
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
