name: Deploy Packages

on:
  push:
    branches:
      - master
    paths:
      - 'ansible/tasks/pkg.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/ansible-base.yaml
    with:
      tags: packages
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
