name: Run Ansible Playbook

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  ansible-playbook:
    runs-on: gha-runner-scale-set-mail-matrix-server
    container:
      image: quay.io/m1k_cloud/automation_docker_image:latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2.8.0
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      with:
        playbook: configure.yml
        directory: ./
        options: |
          -i inventory.yml
