name: Run Ansible Playbook

on:
  push:
    branches:
      - master
    paths:
      - 'files/**'
      - 'group_vars/**'
      - 'tasks/**'
      - configure.yml
      - inventory.yml

  workflow_dispatch:

jobs:
  ansible-playbook:
    runs-on: gha-runner-scale-set-mail-matrix-server
    container:
      image: quay.io/m1k_cloud/automation_docker_image:latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up ssh known hosts
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Set up ssh key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)
        ssh-add -q ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ansible Playbook
      run: ansible-playbook -i inventory.yml configure.yml
      env:
        ANSIBLE_FORCE_COLOR: "True"
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
