name: Full Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'ansible/configure.yml'
      - 'ansible/inventory.yml'
      - 'ansible/group_vars/**'

jobs:
  deploy:
    uses: ./.github/workflows/ansible-base.yaml
    with:
      tags: all
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
