name: Deploy Iptables

on:
  push:
    branches:
      - master
    paths:
      - 'ansible/files/iptables/**'
      - 'ansible/tasks/iptables.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/ansible-base.yaml
    with:
      tags: iptables
    secrets:
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
